using System;
using System.Collections.Generic;
using System.Text;

namespace sorec_gamma.modules.TLV
{
	[Serializable]
    public class TLVTags
    {
		//Objets d'échange WEB-Applicatif SOREC
		public const int SOREC_DATA_TERMINAL = 0xDF8100;

		//SOREC Common tags
		public const int SOREC_TYPE_MESSAGE = 0xDF8001;
		public const int SOREC_CODE_PANNE_LIST = 0xDF8002;
		public const int SOREC_MAC = 0xDF8003;
		public const int SOREC_CODE_REPONSE = 0xDF8004;
		public const int SOREC_DATA_RESPONSE = 0xDF8005;
		public const int SOREC_CODE_PANNE = 0xDF8006;
		public const int SOREC_CODE_PANNE_CODE = 0xDF8007;
		public const int SOREC_CODE_PANNE_DESCRIPTION = 0xDF8008;
		public const int SOREC_CODE_PANNE_TYPE = 0xDF8009;

		//SOREC Authentication Request tags
		public const int SOREC_DATA_TERMINAL_IP = 0xDF8101;
		public const int SOREC_DATA_TERMINAL_LOGIN = 0xDF8102;
		public const int SOREC_DATA_TERMINAL_PASSWORD = 0xDF8103;
		public const int SOREC_DATA_OFFRE = 0xDF8104;
		public const int SOREC_DATA_LOGICIEL = 0xDF8105;
		public const int SOREC_DATA_ATTRIBUTAIRE = 0xDF8106;
		public const int SOREC_DATA_ATTRIBUTAIRE_VERSION = 0xDF8107;
		public const int SOREC_TYPE_TERMINAL = 0xDF8108;
		public const int SOREC_DATA_LOGICIEL_VERSION = 0xDF8112;
		public const int SOREC_DATA_LOGICIEL_DATE_TIME = 0xDF8113;
		public const int SOREC_DATA_SYSTEME_DATE_TIME = 0xDF8115;
		//SOREC Authentication Response tags
		public const int SOREC_AUTORISATION_TERMINAL_JEU = 0xDF8109;
		public const int SOREC_AUTORISATION_TERMINAL_GAIN = 0xDF8110;
		public const int SOREC_AUTORISATION_TERMINAL_TESTMODE = 0xDF8111;
		public const int SOREC_DATA_TERMINAL_POSITION = 0xDF8114;

		//SOREC Authentication attributaire
		public const int SOREC_DATA_ATTRIBUTAIRE_ID = 0xDF8120;
		public const int SOREC_DATA_ATTRIBUTAIRE_CODE = 0xDF8121;
		public const int SOREC_DATA_ATTRIBUTAIRE_LIBELLE = 0xDF8122;
		public const int SOREC_DATA_ATTRIBUTAIRE_PRODUITS_MA = 0xDF8123;
		public const int SOREC_DATA_ATTRIBUTAIRE_PRODUITS_FR = 0xDF8124;
		public const int SOREC_DATA_ATTRIBUTAIRE_PRODUIT = 0xDF8125;
		public const int SOREC_DATA_ATTRIBUTAIRE_PRODUIT_ID = 0xDF8126;
		public const int SOREC_DATA_ATTRIBUTAIRE_PRODUIT_DESIGNATION = 0xDF8127;
		public const int SOREC_DATA_ATTRIBUTAIRE_PRODUIT_LIBELLE = 0xDF8128;
		public const int SOREC_DATA_ATTRIBUTAIRE_PRODUIT_CODE = 0xDF8129;
		public const int SOREC_DATA_ATTRIBUTAIRE_PRODUIT_ENJEU_MIN = 0xDF8130;
		public const int SOREC_DATA_ATTRIBUTAIRE_PRODUIT_ENJEU_MAX = 0xDF8131;
		public const int SOREC_DATA_ATTRIBUTAIRE_PRODUIT_ORDRE = 0xDF8132;
		public const int SOREC_DATA_ATTRIBUTAIRE_PRODUIT_NBR_CHVEAUX_BASE = 0xDF8133;
		public const int SOREC_DATA_ATTRIBUTAIRE_PRODUIT_NBR_MIN_PARTANT = 0xDF8134;
		public const int SOREC_DATA_ATTRIBUTAIRE_PRODUIT_CHAMP_X = 0xDF8135;
		public const int SOREC_DATA_ATTRIBUTAIRE_PRODUIT_EXPRESS = 0xDF8136;
		public const int SOREC_DATA_ATTRIBUTAIRE_PRODUIT_APPARTENANCE = 0xDF8137;
		public const int SOREC_DATA_ATTRIBUTAIRE_PRODUIT_STATUT = 0xDF8138;

		//SOREC DiffusionOffre Response tags
		public const int SOREC_OFFRE = 0xDF8201;
		public const int SOREC_OFFRE_NUMVERSION = 0xDF8202;
		public const int SOREC_OFFRE_TIMESTAMP = 0xDF8203;
		public const int SOREC_OFFRE_REFCONC = 0xDF8204;
		public const int SOREC_OFFRE_REUNIONS = 0xDF8205;
		public const int SOREC_OFFRE_REUNION = 0xDF8206;
		public const int SOREC_OFFRE_REUNION_DATE = 0xDF8207;
		public const int SOREC_OFFRE_REUNION_DIFFUSION = 0xDF8208;
		public const int SOREC_OFFRE_REUNION_NUMERO = 0xDF8209;
		public const int SOREC_OFFRE_REUNION_HIPPODROME = 0xDF8210;
		public const int SOREC_OFFRE_REUNION_HIPPODROME_ORG = 0xDF8211;
		public const int SOREC_OFFRE_REUNION_COURSES = 0xDF8212;
		public const int SOREC_OFFRE_REUNION_COURSE = 0xDF8213;
		public const int SOREC_OFFRE_REUNION_COURSE_NUMERO = 0xDF8214;
		public const int SOREC_OFFRE_REUNION_COURSE_NOM = 0xDF8215;
		public const int SOREC_OFFRE_REUNION_COURSE_HEURE = 0xDF8216;
		public const int SOREC_OFFRE_REUNION_COURSE_PARTICIPANTS = 0xDF8217;
		public const int SOREC_OFFRE_REUNION_COURSE_PARTICIPANT = 0xDF8218;
		public const int SOREC_OFFRE_REUNION_COURSE_PARTICIPANT_NUMERO = 0xDF8219;
		public const int SOREC_OFFRE_REUNION_COURSE_PARTICIPANT_NOM = 0xDF8220;
		public const int SOREC_OFFRE_REUNION_COURSE_PARTICIPANT_ECURIE = 0xDF8221;
		public const int SOREC_OFFRE_REUNION_COURSE_PRODUITS = 0xDF8222;
		public const int SOREC_OFFRE_REUNION_COURSE_PRODUIT = 0xDF8223;
		public const int SOREC_OFFRE_REUNION_COURSE_PRODUIT_CODE = 0xDF8224;
		public const int SOREC_OFFRE_REUNION_COURSE_STATUT = 0xDF8225;
		public const int SOREC_OFFRE_REUNION_COURSE_PRODUIT_STATUT = 0xDF8226;
		public const int SOREC_OFFRE_REUNION_COURSE_PARTICIPANT_STATUT = 0xDF8227;

		//SOREC EnregistrementPari Request tags
		public const int SOREC_DATA_PARI = 0xDF8301;
		public const int SOREC_DATA_PARI_IDCANAL = 0xDF8302;
		public const int SOREC_DATA_PARI_TOTAL_TICKET = 0xDF8303;
		public const int SOREC_DATA_PARI_DATEREUNION = 0xDF8304;
		public const int SOREC_DATA_PARI_NUMREUNION = 0xDF8305;
		public const int SOREC_DATA_PARI_NUMCOURSE = 0xDF8306;
		public const int SOREC_DATA_PARI_FORMULATIONS = 0xDF8307;
		public const int SOREC_DATA_PARI_FORMULATION = 0xDF8308;
		public const int SOREC_DATA_PARI_FORMULATION_CODEPRODUIT = 0xDF8309;
		public const int SOREC_DATA_PARI_FORMULATION_FORMCOMPLETE = 0xDF8310;
		public const int SOREC_DATA_PARI_FORMULATION_DESIGNATION = 0xDF8311;
		public const int SOREC_DATA_PARI_FORMULATION_MISECOMB = 0xDF8312;
		public const int SOREC_DATA_PARI_FORMULATION_MISETOTALE = 0xDF8313;
		public const int SOREC_DATA_PARI_FORMULATION_NUMFORM = 0xDF8314;
		public const int SOREC_DATA_PARI_NUMTICKETANNUL = 0xDF8315;
		public const int SOREC_DATA_PARI_TYPECANAL = 0xDF8322;
		public const int SOREC_DATA_PARI_DATEEMISSION = 0xDF8323;
		public const int SOREC_DATA_PARI_NUMBER_PARTANT_T = 0xDF8326;
		public const int SOREC_DATA_PARI_FORMULATION_CHAMP_X = 0xDF8325;
		//SOREC EnregistrementPari Response tags
		public const int SOREC_DATA_PARI_IDCONC = 0xDF8316;
		public const int SOREC_DATA_PARI_CVNT = 0xDF8317;
		public const int SOREC_DATA_PARI_IDSERVEUR = 0xDF8318;
		public const int SOREC_DATA_COTES = 0xDF8319;
		public const int SOREC_DATA_RAPPORTS = 0xDF8320;
		public const int SOREC_DATA_COMMUNICATIONS = 0xDF8321;
		public const int SOREC_DATA_PARTANT = 0xDF8324;

		//SOREC AnnulationPari Request tags
		public const int SOREC_DATA_TICKET = 0xDF8501;
		public const int SOREC_DATA_TICKET_IDCONC = 0xDF8502;
		public const int SOREC_DATA_TICKET_DATEREUNION = 0xDF8503;
		public const int SOREC_DATA_TICKET_TYPE_ANNUL = 0xDF8504;
		public const int SOREC_DATA_TICKET_MODE_ANNUL = 0xDF8505;
		public const int SOREC_DATA_TICKET_IDSERVER = 0xDF8506;
		public const int SOREC_DATA_TICKET_CVNT = 0xDF8507;
		public const int SOREC_DATA_TICKET_NUMTICKET_ANNUL = 0xDF8508;
		public const int SOREC_DATA_TICKET_TYPECANAL = 0xDF8513;
		//SOREC AnnulationPari Response tags
		public const int SOREC_DATA_TICKET_IDCAN = 0xDF8509;
		public const int SOREC_DATA_TICKET_DATEANNUL = 0xDF8510;
		public const int SOREC_DATA_TICKET_DATEEMISSION = 0xDF8511;
		public const int SOREC_DATA_TICKET_MONTANT = 0xDF8512;
		public const int SOREC_DATA_TICKET_HIPPODROME = 0xDF8515;
		public const int SOREC_DATA_TICKET_NUMEROREUNION = 0xDF8516;
		public const int SOREC_DATA_TICKET_NUMEROCOURSE = 0xDF8517;
		public const int SOREC_DATA_TICKET_DATECOURSE = 0xDF8518;

		//SOREC PaiementTicket Request tags
		public const int SOREC_DATA_TICKET_MODE_PAIEMENT = 0xDF8601;
		//SOREC PaiementTicket Response tags
		public const int SOREC_DATA_TICKET_TYPE_PAIEMENT = 0xDF8602;
		public const int SOREC_DATA_TICKET_DATEPAIEMENT = 0xDF8603;

		//SOREC TraitementTicket Request tags
		public const int SOREC_DATA_TICKET_MODE_OPERATION = 0xDF8604;

		//PRODUIT
		public const int SOREC_DATA_PRODUIT = 0xDF8400;
		public const int SOREC_DATA_PRODUIT_CODE = 0xDF8401;
		public const int SOREC_DATA_PRODUIT_TOTALMISES = 0xDF8402;
		public const int SOREC_DATA_PRODUIT_COMBINAISONS = 0xDF8403;

		//COMBINAISON
		public const int SOREC_DATA_COMBINAISON = 0xDF8404;
		public const int SOREC_DATA_COMBINAISON_COMBINAISON = 0xDF8405;
		public const int SOREC_DATA_COMBINAISON_COTE = 0xDF8406;
		public const int SOREC_DATA_COMBINAISON_TOTALMISES = 0xDF8407;

		//RAPPORT
		public const int SOREC_DATA_RAPPORT = 0xDF8408;
		public const int SOREC_DATA_RAPPORT_COMBINAISON = 0xDF8409;
		public const int SOREC_DATA_RAPPORT_RAPPORT = 0xDF8410;
		public const int SOREC_DATA_RAPPORT_TYPE = 0xDF8411;
		public const int SOREC_DATA_RAPPORT_TOTALMISES = 0xDF8412;
		public const int SOREC_DATA_EVENEMENT_RAPPORTS = 0xDF8447;
		public const int SOREC_DATA_EVENEMENT_RAPPORT = 0xDF8429;
		public const int SOREC_DATA_EVENEMENT_RAPPORT_TIMESTAMP = 0xDF8430;
		public const int SOREC_DATA_EVENEMENT_RAPPORT_REFCALC = 0xDF8431;
		public const int SOREC_DATA_EVENEMENT_RAPPORT_VERSION = 0xDF8432;
		public const int SOREC_DATA_EVENEMENT_RAPPORT_DATE = 0xDF8433;
		public const int SOREC_DATA_EVENEMENT_RAPPORT_REUNION = 0xDF8434;
		public const int SOREC_DATA_EVENEMENT_RAPPORT_COURSE = 0xDF8435;
		public const int SOREC_DATA_EVENEMENT_RAPPORT_PRODUITS = 0xDF8436;
		public const int SOREC_DATA_EVENEMENT_RAPPORT_PRODUIT = 0xDF8437;
		public const int SOREC_DATA_EVENEMENT_RAPPORT_PRODUIT_CODE = 0xDF8438;
		public const int SOREC_DATA_EVENEMENT_RAPPORT_PRODUIT_MISES = 0xDF8439;
		public const int SOREC_DATA_EVENEMENT_RAPPORT_PRODUIT_STATUT = 0xDF8440;
		public const int SOREC_DATA_EVENEMENT_RAPPORT_PRODUIT_RAPPORTS = 0xDF8441;
		public const int SOREC_DATA_EVENEMENT_RAPPORT_PRODUIT_RAPPORT = 0xDF8442;
		public const int SOREC_DATA_EVENEMENT_RAPPORT_PRODUIT_RAPPORT_COMBINAISON = 0xDF8443;
		public const int SOREC_DATA_EVENEMENT_RAPPORT_PRODUIT_RAPPORT_MISES = 0xDF8444;
		public const int SOREC_DATA_EVENEMENT_RAPPORT_PRODUIT_RAPPORT_RAPPORT = 0xDF8445;
		public const int SOREC_DATA_EVENEMENT_RAPPORT_PRODUIT_RAPPORT_TYPE = 0xDF8446;

		//DATA_EVENEMENT
		public const int SOREC_DATA_EVENEMENT = 0xDF8413;
		public const int SOREC_DATA_EVENEMENT_IDENTIFIANT = 0xDF8414;
		public const int SOREC_DATA_EVENEMENT_TIMESTAMP = 0xDF8415;
		public const int SOREC_DATA_EVENEMENT_DATEREUNION = 0xDF8416;
		public const int SOREC_DATA_EVENEMENT_NUMREUNION = 0xDF8417;
		public const int SOREC_DATA_EVENEMENT_NUMCOURSE = 0xDF8418;
		public const int SOREC_DATA_EVENEMENT_STATUT = 0xDF8419;
		public const int SOREC_DATA_EVENEMENT_PRODUITS = 0xDF8420;
		public const int SOREC_DATA_EVENEMENT_CODE_PRODUIT = 0xDF8448;

		//COMMUNICATION
		public const int SOREC_DATA_COMMUNICATION = 0xDF8421;
		public const int SOREC_DATA_COMMUNICATION_OBJ = 0xDF8422;
		public const int SOREC_DATA_COMMUNICATION_TYPE = 0xDF8423;
		public const int SOREC_DATA_COMMUNICATION_CORPS = 0xDF8424;
		public const int SOREC_DATA_COMMUNICATION_DUREE = 0xDF8425;
		public const int SOREC_DATA_COMMUNICATION_DATED = 0xDF8426;
		public const int SOREC_DATA_COMMUNICATION_DATEF = 0xDF8427;
		public const int SOREC_DATA_COMMUNICATION_PDV = 0xDF8428;

		//SIGNAL
		public const int SOREC_DATA_SIGNAL = 0xDF8600;
		public const int SOREC_DATA_SIGNAL_IDENTIFIANT = 0xDF8601;
		public const int SOREC_DATA_SIGNAL_EVENEMENT_TIMESTAMP = 0xDF8602;
		public const int SOREC_DATA_SIGNAL_DATEREUNION = 0xDF8603;
		public const int SOREC_DATA_SIGNAL_NUMEROREUNION = 0xDF8604;
		public const int SOREC_DATA_SIGNAL_NUMEROCOURSE = 0xDF8605;
		public const int SOREC_DATA_SIGNAL_STATUTCOURSE = 0xDF8606;
		public const int SOREC_DATA_SIGNAL_RESULTATS = 0xDF8607;
		public const int SOREC_DATA_SIGNAL_NUMEROPARTANT = 0xDF8608;
		public const int SOREC_DATA_SIGNAL_STATUTPARTANT = 0xDF8609;
		public const int SOREC_DATA_SIGNAL_STATUTPRODUIT = 0xDF8610;
		public const int SOREC_DATA_SIGNAL_LISTEPRODUITS = 0xDF8611;
		public const int SOREC_DATA_SIGNAL_CODEPRODUIT = 0xDF8612;
		public const int SOREC_DATA_SIGNAL_PRODUIT = 0xDF8613;
		public const int SOREC_DATA_SIGNAL_PARTANT = 0xDF8614;
		public const int SOREC_DATA_SIGNAL_LISTEPARTANTS = 0xDF8615;
		public const int SOREC_DATA_SIGNAL_VERSION_OFFRE = 0xDF8616;
		public const int SOREC_DATA_SIGNAL_NOMPARTANT = 0xDF8617;
		public const int SOREC_DATA_SIGNAL_ECURIEPARTANT = 0xDF8618;

		//COTES
		public const int SOREC_DATA_COTES_MSG = 0xDF8620;
		public const int SOREC_DATA_COTES_IDENTIFIANT = 0xDF8621;
		public const int SOREC_DATA_COTES_EVENEMENT_TIMESTAMP = 0xDF8622;
		public const int SOREC_DATA_COTES_DATEREUNION = 0xDF8623;
		public const int SOREC_DATA_COTES_NUMEROREUNION = 0xDF8624;
		public const int SOREC_DATA_COTES_NUMEROCOURSE = 0xDF8625;
		public const int SOREC_DATA_COTES_STATUT = 0xDF8626;
		public const int SOREC_DATA_COTES_LISTEPRODUITS = 0xDF8627;
		public const int SOREC_DATA_COTES_CODEPRODUIT = 0xDF8628;
		public const int SOREC_DATA_COTES_TOTALMISES_PRODUIT = 0xDF8629;
		public const int SOREC_DATA_COTES_PRODUIT = 0xDF8630;
		public const int SOREC_DATA_COTES_LISTECOMBINAISONS = 0xDF8631;
		public const int SOREC_DATA_COTES_COMB = 0xDF8632;
		public const int SOREC_DATA_COTES_COMBINAISON_COTE = 0xDF8633;
		public const int SOREC_DATA_COTES_COMBINAISON_TOTALMISES = 0xDF8634;
		public const int SOREC_DATA_COTES_COMBINAISON = 0xDF8635;
		public const int SOREC_DATA_COTES_COURSES = 0xDF8636;
		public const int SOREC_DATA_COTES_COURSE = 0xDF8637;
		public const int SOREC_DATA_COTES_REUNIONS = 0xDF8638;
		public const int SOREC_DATA_COTES_REUNION = 0xDF8639;

		//PDV
		public const int SOREC_DATA_PDV = 0xDF8800;
		public const int SOREC_DATA_PDV_CUMUL = 0xDF8801;
		public const int SOREC_DATA_SOLDE_PREPAYE = 0xDF8802;
		public const int SOREC_DATA_NUMERO_PDV = 0xDF8803;
		public const int SOREC_DATA_PDV_PLAFOND = 0xDF8804;

		// COMPTE
		public const int SOREC_DATA_COMPTE = 0xDF8700;
		public const int SOREC_DATA_COMPTE_CIN = 0xDF8701;
		public const int SOREC_DATA_COMPTE_NOM = 0xDF8702;
		public const int SOREC_DATA_COMPTE_PRENOM = 0xDF8703;
		public const int SOREC_DATA_COMPTE_TELEPHONE = 0xDF8704;
		public const int SOREC_DATA_COMPTE_DATE_NAISSANCE = 0xDF8705;
		public const int SOREC_DATA_COMPTE_STATUT = 0xDF8706;
		public const int SOREC_DATA_COMPTE_MONTANT_ALIMENTATION = 0xDF8707;
		public const int SOREC_DATA_COMPTE_EMAIL = 0xDF8708;
		public const int SOREC_DATA_COMPTE_ERROR = 0xDF8709;
		public const int SOREC_DATA_COMPTE_ERROR_CODE = 0xDF8710;
		public const int SOREC_DATA_COMPTE_ERROR_PROPERTY = 0xDF8711;
		public const int SOREC_DATA_COMPTE_ERROR_MESSAGE = 0xDF8712;
		public const int SOREC_DATA_COMPTE_ERROR_LIST = 0xDF8712;

		// FSOLD
		public const int SOREC_DATA_FSOLD = 0xDF8720;
		public const int SOREC_DATA_FSOLD_DATE = 0xDF8721;
		public const int SOREC_DATA_FSOLD_NUMERO_TICKETANNUL = 0xDF8722;
		public const int SOREC_DATA_FSOLD_CONTENT = 0xDF8723;
		public const int SOREC_DATA_FSOLD_CODEPDV = 0xDF8724;

		// VOUCHER
		public const int SOREC_DATA_VOUCHER = 0xDF8740;
		public const int SOREC_DATA_VOUCHER_IDENTIFIANTCAN = 0xDF8741;
		public const int SOREC_DATA_VOUCHER_MONTANT = 0xDF8742;
		public const int SOREC_DATA_VOUCHER_NUMERO_TICKETANNUL = 0xDF8743;
		public const int SOREC_DATA_VOUCHER_IDENTIFIANTCONC = 0xDF8744;
		public const int SOREC_DATA_VOUCHER_CVNV = 0xDF8745;
		public const int SOREC_DATA_VOUCHER_IDSERVEUR = 0xDF8746;
		public const int SOREC_DATA_VOUCHER_DATEEXP = 0xDF8747;
		public const int SOREC_DATA_VOUCHER_DATEEMISSION = 0xDF8748;
		public const int SOREC_DATA_VOUCHER_MODEPAIEMENT = 0xDF8749;
		public const int SOREC_DATA_VOUCHER_DATEPAIEMENT = 0xDF8750;
		public const int SOREC_DATA_VOUCHER_TYPEPAIEMENT = 0xDF8751;
		public const int SOREC_DATA_VOUCHER_DATESESSION = 0xDF8752;

		//GAGNANT
		public const int SOREC_DATA_GAGNANT = 0xDF8760;
		public const int SOREC_DATA_GAGNANT_IDENTIFIANTCAN = 0xDF8761;
		public const int SOREC_DATA_GAGNANT_IDENTIFIANTCONC = 0xDF8762;
		public const int SOREC_DATA_GAGNANT_CIN = 0xDF8763;
		public const int SOREC_DATA_GAGNANT_NOM = 0xDF8764;
		public const int SOREC_DATA_GAGNANT_PRENOM = 0xDF8765;
		public const int SOREC_DATA_GAGNANT_TELEPHONE = 0xDF8766;
		public const int SOREC_DATA_GAGNANT_COMMENTAIRE = 0xDF8767;
		public const int SOREC_DATA_GAGNANT_DATEREUNION = 0xDF8768;
		public const int SOREC_DATA_GAGNANT_IDSERVEUR = 0xDF8769;
		public const int SOREC_DATA_GAGNANT_TYPEPAIEMENT = 0xDF8770;
		public const int SOREC_DATA_GAGNANT_DATEPAIEMENT = 0xDF8771;
		public const int SOREC_DATA_GAGNANT_DATEEMISSION = 0xDF8772;
		public const int SOREC_DATA_GAGNANT_MONTANTGAIN = 0xDF8773;
		public const int SOREC_DATA_GAGNANT_HIPPODROME = 0xDF8774;
		public const int SOREC_DATA_GAGNANT_NUMEROREUNION = 0xDF8775;
		public const int SOREC_DATA_GAGNANT_NUMEROCOURSE = 0xDF8776;
		public const int SOREC_DATA_GAGNANT_DATECOURSE = 0xDF8777;

		//ETAT CAISSE
		public const int SOREC_DATA_ETAT_CAISSE = 0xDF8000;
		public const int SOREC_DATA_ETAT_CAISSE_DATE = 0xDF8001;
		public const int SOREC_DATA_ETAT_CAISSE_TYPE = 0xDF8002;
		public const int SOREC_DATA_ETAT_CAISSE_PARIS = 0xDF8003;
		public const int SOREC_DATA_ETAT_CAISSE_PARIS_NOMBRE = 0xDF8004;
		public const int SOREC_DATA_ETAT_CAISSE_PARIS_CUMUL = 0xDF8005;
		public const int SOREC_DATA_ETAT_CAISSE_ANNULATIONS = 0xDF8006;
		public const int SOREC_DATA_ETAT_CAISSE_ANNULATIONS_NOMBRE = 0xDF8007;
		public const int SOREC_DATA_ETAT_CAISSE_ANNULATIONS_CUMUL = 0xDF8008;
		public const int SOREC_DATA_ETAT_CAISSE_VOUCHERS = 0xDF8009;
		public const int SOREC_DATA_ETAT_CAISSE_VOUCHERS_NOMBRE = 0xDF8010;
		public const int SOREC_DATA_ETAT_CAISSE_VOUCHERS_CUMUL = 0xDF8011;
		public const int SOREC_DATA_ETAT_CAISSE_VOUCHERS_PAIEMENT = 0xDF8012;
		public const int SOREC_DATA_ETAT_CAISSE_VOUCHERS_PAIEMENT_NOMBRE = 0xDF8013;
		public const int SOREC_DATA_ETAT_CAISSE_VOUCHERS_PAIEMENT_CUMUL = 0xDF8014;
		public const int SOREC_DATA_ETAT_CAISSE_NOMBRE_GUICHETS = 0xDF8015;
		public const int SOREC_DATA_ETAT_CAISSE_DEPOTS_COMPTES = 0xDF8016;
		public const int SOREC_DATA_ETAT_CAISSE_DEPOTS_COMPTES_NOMBRE = 0xDF8017;
		public const int SOREC_DATA_ETAT_CAISSE_DEPOTS_COMPTES_CUMUL = 0xDF8018;
		public const int SOREC_DATA_ETAT_CAISSE_ANNULATIONS_SYSTEME = 0xDF8040;
		public const int SOREC_DATA_ETAT_CAISSE_ANNULATIONS_SYSTEME_NOMBRE = 0xDF8041;
		public const int SOREC_DATA_ETAT_CAISSE_ANNULATIONS_SYSTEME_CUMUL = 0xDF8042;
		public const int SOREC_DATA_ETAT_CAISSE_ANNULATIONS_MACHINE = 0xDF8046;
		public const int SOREC_DATA_ETAT_CAISSE_ANNULATIONS_MACHINE_NOMBRE = 0xDF8047;
		public const int SOREC_DATA_ETAT_CAISSE_ANNULATIONS_MACHINE_CUMUL = 0xDF8048;
		public const int SOREC_DATA_ETAT_CAISSE_PAIEMENTS = 0xDF8043;
		public const int SOREC_DATA_ETAT_CAISSE_PAIEMENTS_NOMBRE = 0xDF8044;
		public const int SOREC_DATA_ETAT_CAISSE_PAIEMENTS_CUMUL = 0xDF8045;

		// Annulation paiement systeme
		public const int SOREC_DATA_ANNU_PAI_SYSTEME = 0xDF8020;
		public const int SOREC_DATA_ANNU_PAI_SYSTEME_PARI = 0xDF8021;
		public const int SOREC_DATA_ANNU_PAI_SYSTEME_PARI_DATE_REUNION = 0xDF8022;
		public const int SOREC_DATA_ANNU_PAI_SYSTEME_PARI_NUMERO_TICKET = 0xDF8023;
		public const int SOREC_DATA_ANNU_PAI_SYSTEME_PARI_NUMERO_REUNION = 0xDF8024;
		public const int SOREC_DATA_ANNU_PAI_SYSTEME_PARI_NUMERO_COURSE = 0xDF8025;
		public const int SOREC_DATA_ANNU_PAI_SYSTEME_VOUCHER = 0xDF8026;
		public const int SOREC_DATA_ANNU_PAI_SYSTEME_VOUCHER_DATE_SESSION = 0xDF8027;
		public const int SOREC_DATA_ANNU_PAI_SYSTEME_VOUCHER_NUMERO_TICKET = 0xDF8028;

		//MAJ Logicielle
		public const int SOREC_MAJ_LOGICIELLE = 0xDF8030;
		public const int SOREC_MAJ_LOGICIELLE_STATUT = 0xDF8031;
		public const int SOREC_MAJ_LOGICIEL_VERSION = 0xDF8032;
		public const int SOREC_MAJ_LOGICIEL_DATE_MAJ = 0xDF8033;

		// RECONCILIATION
		public const int SOREC_DATA_RECONCILIATION = 0xDF8034;

		public int tag; 
		public int length;
		public byte[] value;               

		public TLVTags(int tag, int length, byte[] value)
		{
			this.tag = tag;
			this.length = length;
			this.value = value;
		}

        public TLVTags()
		{
		}

        public override string ToString()
        {
            return string.Format("TLV => Tag: {0}, Length: {1}, Value: {2}", tag, length, value);
        }

    }

}